action_id: trunk-upgrade-available
date: 2024-02-17 17:00:52
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1708189252
full_timestamp:
  nanos: 233693000
  seconds: 1708189252
trunk_version: 1.20.0
